[package]
name = "tdigest"
version = "0.1.0"
authors = ["Ryan P. Brewster <RyanPBrewster@gmail.com>"]

[dependencies]
rand = "0.5.5"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "simple"
harness = false
